### ISSUE TITLE
Hanxi <--> Supawit Tasks

### ISSUE THREAD

**Issue by mIXs222** [illinoisdata/kishu#117]
@iq180fq200 @mIXs222 

- [x] Checkout with deletion and stable branch name (#116)
  - [ ] (Hanxi) Confirm fixes
- [x] Issue saving on ipylab (#116)
  - [x] #120
- [x] Checkout not auto-commit (#116)
  - [x] (Hanxi) Confirm fixes
- [x] Return HEAD (#118)
  - [ ] (Hanxi) Confirm feature
- [x] Rebranch too aggressive (#135)
  - [ ] (Hanxi) Confirm fixes
- [x] Multiple branches per commit (#126)
  - [x] (Hanxi) Change JSON schema
  - [ ] (Hanxi) Confirm feature
- [x] Recover notebook cells (#136)
  - [ ] (Supawit) FIX: auto-reload (#138)
- [x] Support tag (#175)
  - [ ] (Hanxi) Confirm feature
- [x] Update schema (branch list, commit detail) (#176)
  - [ ] (Hanxi) Confirm feature
- [x] Capture executed cell (#184)
- [x] Partial Checkouts + code/variable version (#179 and #186)
- [x] Tag delete and modify (#251)
- [ ] Capture recently executed cells (#113)
- [ ] Boolean search query
