### ISSUE TITLE
Kishu CLI Progress Tracker

### ISSUE THREAD

**Issue by pyongjoo** [illinoisdata/kishu#201]
- [x] `kishu commit NOTEBOOK [-m MESSAGE]`
  - [x] Presentation layer #241 
  - [x] Needs to handle uninitialized notebook #241 
- [x] `kishu checkout NOTEBOOK ( BRANCH_NAME | COMMIT_ID )`
  - [x] Presentation layer #241 
  - [x] Needs to handle uninitialized notebook #241 
  - [x] Commit prefix disambiguation (#205)
- [x] `kishu branch NOTEBOOK [-c NEW_BRANCH_NAME COMMIT_ID] [-m OLD_BRANCH_NAME NEW_BRANCH_NAME] [-d DELETE_BRANCH_NAME]`
  - [x] `[-d DELETE_BRANCH_NAME]` (#200)
  - [ ] Presentation layer
  - [ ] Needs to make COMMIT_ID required only under `-c` flag
- [x] `kishu tag NOTEBOOK TAG_NAME COMMIT_ID [-m MESSAGE]`
  - [ ] Presentation layer
- [x] `kishu init NOTEBOOK_PATH`
  - [x] Presentation layer (#226)
- [x] `kishu detach NOTEBOOK_PATH` (#212)
  - [x] Presentation layer (#226)
- [x] `kishu log NOTEBOOK [COMMIT_ID] [ -a | --all ]`
  - [ ] Presentation layer
- [x] `kishu list [ -a | -all ]`
  - [ ] Presentation layer
